name: Docker Push
on:
  release:
    types:
      - created
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build image
      uses: mr-smithers-excellent/docker-build-push@v2
      with:
        image: remotelyplatform/ascode
        registry: docker.io
        username: remotelyplatform
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag image
      uses: mr-smithers-excellent/docker-build-push@v2
      with:
        image: remotelyplatform/ascode
        registry: docker.io
        tag: latest
        username: remotelyplatform
        password: ${{ secrets.DOCKER_PASSWORD }}